#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["RoyalKiddiesWard.API/RoyalKiddiesWard.API.csproj", "RoyalKiddiesWard.API/"]
RUN dotnet restore "RoyalKiddiesWard.API/RoyalKiddiesWard.API.csproj"
COPY . .
WORKDIR "/src/RoyalKiddiesWard.API"
RUN dotnet build "RoyalKiddiesWard.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RoyalKiddiesWard.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RoyalKiddiesWard.API.dll"]
# Docker image